const { BASE_URL } = process.env;

export const dbData = {
    dokan: {
        optionName: {
            general: 'dokan_general',
            selling: 'dokan_selling',
            withdraw: 'dokan_withdraw',
            reverseWithdraw: 'dokan_reverse_withdrawal',
            page: 'dokan_pages',
            appearance: 'dokan_appearance',
            menuManager: 'dokan_menu_manager',
            privacyPolicy: 'dokan_privacy',
            colors: 'dokan_colors',
            // liveSearch: 'dokan_live_search_setting',
            storeSupport: 'dokan_store_support_setting',
            // sellerVerification: 'dokan_verification',
            // verificationSMSGateways: 'dokan_verification_sms_gateways',
            emailVerification: 'dokan_email_verification',
            // socialApi: 'dokan_social_api',
            shippingStatus: 'dokan_shipping_status_setting',
            quote: 'dokan_quote_settings',
            // liveChat: 'dokan_live_chat',
            rma: 'dokan_rma',
            wholesale: 'dokan_wholesale',
            euCompliance: 'dokan_germanized',
            deliveryTime: 'dokan_delivery_time',
            productAdvertising: 'dokan_product_advertisement',
            geolocation: 'dokan_geolocation',
            productReportAbuse: 'dokan_report_abuse',
            spmv: 'dokan_spmv',
            vendorSubscription: 'dokan_product_subscription',
            // vendorAnalytics:
            dokanActiveModules: 'dokan_pro_active_modules',

            // dokanPro
            dokanProLicense: 'dokan_pro_license',
            dokanProActiveModules: 'dokan_pro_active_modules',
        },

        generalSettings: {
            // site settings
            site_options: '',
            admin_access: 'on', // vendor edit product test needs it to disable
            custom_store_url: 'store',
            setup_wizard_logo_url: '',
            setup_wizard_message:
                '<p>Thank you for choosing The Marketplace to power your online store! This quick setup wizard will help you configure the basic settings. <strong>It&rsquo;s completely optional and shouldn&rsquo;t take longer than two minutes.<strong></p>',
            disable_welcome_wizard: 'off',
            global_digital_mode: 'sell_both',
            enable_shipstation_logging: 'off',
            data_clear_on_uninstall: 'off',

            // vendor store settings
            vendor_store_options: '',
            seller_enable_terms_and_conditions: 'on',
            store_products_per_page: '12',
            enabled_address_on_reg: 'off',
            enable_tc_on_reg: 'on',
            enable_single_seller_mode: 'off',
            store_category_type: 'multiple', // none, multiple

            // product page settings
            product_page_options: '',
            show_vendor_info: 'on',
            enabled_more_products_tab: 'on',
        },

        sellingSettings: {
            // commission
            selling_capabilities: '',
            commission_type: 'percentage',
            admin_percentage: '10',
            shipping_fee_recipient: 'seller',
            tax_fee_recipient: 'seller',
            shipping_tax_fee_recipient: 'seller',
            automatic_process_api_refund: 'off',

            // vendor capabilities
            additional_fee: '10',
            new_seller_enable_selling: 'on',
            one_step_product_create: 'on',
            disable_product_popup: 'off',
            order_status_change: 'on',
            dokan_any_category_selection: 'off',
            product_status: 'publish',
            vendor_duplicate_product: 'on',
            product_category_style: 'single',
            product_vendors_can_create_tags: 'on',
            add_new_attribute: 'on',
            discount_edit: {
                'order-discount': 'order-discount',
                'product-discount': 'product-discount',
            },
            hide_customer_info: 'off',
            seller_review_manage: 'on',
            new_seller_enable_auction: 'on',
            enable_guest_user_enquiry: 'on',
            enable_min_max_quantity: 'on',
            enable_min_max_amount: 'on',
            disable_shipping_tab: 'off',

            // catalog mode
            catalog_mode_settings: '',
            catalog_mode_hide_add_to_cart_button: 'on',
            catalog_mode_hide_product_price: 'on',
        },

        withdrawSettings: {
            // withdraw settings
            withdraw_methods: {
                paypal: 'paypal',
                bank: 'bank',
                dokan_custom: 'dokan_custom',
                skrill: 'skrill',
            },
            withdraw_method_name: 'Bksh',
            withdraw_method_type: 'Phone',
            withdraw_charges: {
                paypal: {
                    fixed: '0',
                    percentage: '5',
                },
                bank: {
                    fixed: '5',
                    percentage: '',
                },
                skrill: {
                    fixed: '0',
                    percentage: '0',
                },
                dokan_custom: {
                    fixed: '0',
                    percentage: '0',
                },
            },
            withdraw_limit: '10',
            withdraw_order_status: {
                'wc-completed': 'wc-completed',
                'wc-processing': 'wc-processing',
            },
            exclude_cod_payment: 'off',
            withdraw_date_limit: '0',
            hide_withdraw_option: 'off',

            // disbursement settings
            disbursement_schedule_settings: '',
            disbursement: {
                manual: 'manual',
                schedule: 'schedule',
            },
            disbursement_schedule: {
                quarterly: 'quarterly',
                monthly: 'monthly',
                biweekly: 'biweekly',
                weekly: 'weekly',
            },
            quarterly_schedule: {
                month: 'march',
                week: '1',
                days: 'monday',
            },
            monthly_schedule: {
                week: '1',
                days: 'monday',
            },
            biweekly_schedule: {
                week: '1',
                days: 'monday',
            },
            weekly_schedule: 'monday',
            send_announcement_for_payment_change: 'false',
            send_announcement_for_disbursement_schedule_change: 'false',
        },

        reverseWithdrawSettings: {
            enabled: 'on',
            payment_gateways: {
                cod: 'cod',
            },
            billing_type: 'by_amount',
            reverse_balance_threshold: '10',
            monthly_billing_day: '1',
            due_period: '0',
            failed_actions: {
                enable_catalog_mode: 'enable_catalog_mode',
                hide_withdraw_menu: 'hide_withdraw_menu',
                status_inactive: 'status_inactive',
            },
            display_notice: 'on',
            send_announcement: 'on',
        },

        pageSettings: {
            dashboard: '4',
            store_listing: '5',
            my_orders: '6',
            reg_tc_page: '2',
        },

        appearanceSettings: {
            appearance_options: '',
            store_map: 'on',
            map_api_source: 'google_maps',
            gmap_api_key: process.env.GMAP,
            mapbox_access_token: '',
            recaptcha_validation_label: '',
            contact_seller: 'on',
            store_header_template: 'default',
            store_banner_width: '625',
            store_banner_height: '300',
            store_open_close: 'on',
            enable_theme_store_sidebar: 'off',
            hide_vendor_info: {
                email: '',
                phone: '',
                address: '',
            },
            disable_dokan_fontawesome: 'off',
        },

        menuManagerSettings: {
            menu_manager_menu_tab: '',
            dashboard_menu_manager: {
                left_menus: {
                    dashboard: {
                        menu_key: 'dashboard',
                        is_sortable: 'false',
                        previous_title: 'Dashboard',
                        menu_manager_title: 'Dashboard',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'false',
                        is_switched_on: 'true',
                        menu_manager_position: '0',
                        title: 'Dashboard',
                        icon: '<i class="fas fa-tachometer-alt"></i>',
                        url: `${BASE_URL}/dashboard/`,
                        pos: '10',
                        permission: 'dokan_view_overview_menu',
                    },
                    products: {
                        menu_key: 'products',
                        is_sortable: 'true',
                        previous_title: 'Products',
                        menu_manager_title: 'Products',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '1',
                        title: 'Products',
                        icon: '<i class="fas fa-briefcase"></i>',
                        url: `${BASE_URL}/dashboard/products/`,
                        pos: '30',
                        permission: 'dokan_view_product_menu',
                    },
                    orders: {
                        menu_key: 'orders',
                        is_sortable: 'true',
                        previous_title: 'Orders',
                        menu_manager_title: 'Orders',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '2',
                        title: 'Orders',
                        icon: '<i class="fas fa-shopping-cart"></i>',
                        url: `${BASE_URL}/dashboard/orders/`,
                        pos: '50',
                        permission: 'dokan_view_order_menu',
                    },
                    'user-subscription': {
                        menu_key: 'user-subscription',
                        is_sortable: 'true',
                        previous_title: 'User Subscriptions',
                        menu_manager_title: 'User Subscriptions',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '3',
                        title: 'User Subscriptions',
                        icon: '<i class="fas fa-users"></i>',
                        url: `${BASE_URL}/dashboard/user-subscription/`,
                        pos: '50',
                        permission: 'dokan_view_order_menu',
                    },
                    'requested-quotes': {
                        menu_key: 'requested-quotes',
                        is_sortable: 'true',
                        previous_title: 'Request Quotes',
                        menu_manager_title: 'Request Quotes',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '4',
                        title: 'Request Quotes',
                        icon: '<i class="fa fa-list" aria-hidden="true"></i>',
                        url: `${BASE_URL}/dashboard/requested-quotes/`,
                        pos: '53',
                        permission: 'dokan_view_request_quote_menu',
                    },
                    coupons: {
                        menu_key: 'coupons',
                        is_sortable: 'true',
                        previous_title: 'Coupons',
                        menu_manager_title: 'Coupons',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '5',
                        title: 'Coupons',
                        icon: '<i class="fas fa-gift"></i>',
                        url: `${BASE_URL}/dashboard/coupons/`,
                        pos: '55',
                        permission: 'dokan_view_coupon_menu',
                    },
                    reports: {
                        menu_key: 'reports',
                        is_sortable: 'true',
                        previous_title: 'Reports',
                        menu_manager_title: 'Reports',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '6',
                        title: 'Reports',
                        icon: '<i class="fas fa-chart-line"></i>',
                        url: `${BASE_URL}/dashboard/reports/`,
                        pos: '60',
                        permission: 'dokan_view_report_menu',
                    },
                    'delivery-time-dashboard': {
                        menu_key: 'delivery-time-dashboard',
                        is_sortable: 'true',
                        previous_title: 'Delivery Time',
                        menu_manager_title: 'Delivery Time',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '7',
                        title: 'Delivery Time',
                        icon: '<i class="far fa-clock"></i>',
                        url: `${BASE_URL}/dashboard/delivery-time-dashboard/`,
                        pos: '61',
                    },
                    reviews: {
                        menu_key: 'reviews',
                        is_sortable: 'true',
                        previous_title: 'Reviews',
                        menu_manager_title: 'Reviews',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '8',
                        title: 'Reviews',
                        icon: '<i class="far fa-comments"></i>',
                        url: `${BASE_URL}/dashboard/reviews/`,
                        pos: '65',
                        permission: 'dokan_view_review_menu',
                    },
                    withdraw: {
                        menu_key: 'withdraw',
                        is_sortable: 'true',
                        previous_title: 'Withdraw',
                        menu_manager_title: 'Withdraw',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '9',
                        title: 'Withdraw',
                        icon: '<i class="fas fa-upload"></i>',
                        url: `${BASE_URL}/dashboard/withdraw/`,
                        pos: '70',
                        permission: 'dokan_view_withdraw_menu',
                    },
                    'reverse-withdrawal': {
                        menu_key: 'reverse-withdrawal',
                        is_sortable: 'true',
                        previous_title: 'Reverse Withdrawal',
                        menu_manager_title: 'Reverse Withdrawal',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '10',
                        title: 'Reverse Withdrawal',
                        icon: '<i class="fas fa-dollar-sign"></i>',
                        url: `${BASE_URL}/dashboard/reverse-withdrawal/`,
                        pos: '71',
                        permission: 'dokan_view_withdraw_menu',
                    },
                    'seller-badge': {
                        menu_key: 'seller-badge',
                        is_sortable: 'true',
                        previous_title: 'Badge',
                        menu_manager_title: 'Badge',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '11',
                        title: 'Badge',
                        icon: '<i class="fas fa-award"></i>',
                        url: `${BASE_URL}/dashboard/seller-badge/`,
                        pos: '73',
                        permission: 'dokan_view_badge_menu',
                    },
                    'product-questions-answers': {
                        menu_key: 'product-questions-answers',
                        is_sortable: 'true',
                        previous_title: 'Product Q&A',
                        menu_manager_title: 'Product Q&A',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '12',
                        title: 'Product Q&A',
                        icon: '<i class="far fa-question-circle" aria-hidden="true"></i>',
                        url: `${BASE_URL}/dashboard/product-questions-answers/`,
                        pos: '80',
                        permission: 'dokandar',
                    },
                    'return-request': {
                        menu_key: 'return-request',
                        is_sortable: 'true',
                        previous_title: 'Return Request',
                        menu_manager_title: 'Return Request',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '13',
                        title: 'Return Request',
                        icon: '<i class="fas fa-undo-alt" aria-hidden="true"></i>',
                        url: `${BASE_URL}/dashboard/return-request/`,
                        pos: '170',
                        permission: 'dokan_view_store_rma_menu',
                    },
                    staffs: {
                        menu_key: 'staffs',
                        is_sortable: 'true',
                        previous_title: 'Staff',
                        menu_manager_title: 'Staff',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '14',
                        title: 'Staff',
                        icon: '<i class="fas fa-users"></i>',
                        url: `${BASE_URL}/dashboard/staffs/`,
                        pos: '172',
                    },
                    followers: {
                        menu_key: 'followers',
                        is_sortable: 'true',
                        previous_title: 'Followers',
                        menu_manager_title: 'Followers',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '15',
                        title: 'Followers',
                        icon: '<i class="fas fa-heart"></i>',
                        url: `${BASE_URL}/dashboard/followers/`,
                        pos: '175',
                        permission: 'dokan_view_overview_menu',
                    },
                    booking: {
                        menu_key: 'booking',
                        is_sortable: 'true',
                        previous_title: 'Booking',
                        menu_manager_title: 'Booking',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '16',
                        title: 'Booking',
                        icon: '<i class="far fa-calendar-alt"></i>',
                        url: `${BASE_URL}/dashboard/booking/`,
                        pos: '180',
                    },
                    announcement: {
                        menu_key: 'announcement',
                        is_sortable: 'true',
                        previous_title: 'Announcements',
                        menu_manager_title: 'Announcements',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '17',
                        title: 'Announcements',
                        icon: '<i class="fas fa-bell"></i>',
                        url: `${BASE_URL}/dashboard/announcement/`,
                        pos: '181',
                    },
                    analytics: {
                        menu_key: 'analytics',
                        is_sortable: 'true',
                        previous_title: 'Analytics',
                        menu_manager_title: 'Analytics',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '18',
                        title: 'Analytics',
                        icon: '<i class="fas fa-chart-area"></i>',
                        url: `${BASE_URL}/dashboard/analytics/`,
                        pos: '182',
                    },
                    tools: {
                        menu_key: 'tools',
                        is_sortable: 'true',
                        previous_title: 'Tools',
                        menu_manager_title: 'Tools',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '19',
                        title: 'Tools',
                        icon: '<i class="fas fa-wrench"></i>',
                        url: `${BASE_URL}/dashboard/tools/`,
                        pos: '183',
                    },
                    auction: {
                        menu_key: 'auction',
                        is_sortable: 'true',
                        previous_title: 'Auction',
                        menu_manager_title: 'Auction',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '20',
                        title: 'Auction',
                        icon: '<i class="fas fa-gavel"></i>',
                        url: `${BASE_URL}/dashboard/auction/`,
                        pos: '185',
                        permission: 'dokan_view_auction_menu',
                    },
                    support: {
                        menu_key: 'support',
                        is_sortable: 'true',
                        previous_title: 'Support',
                        menu_manager_title: 'Support',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '21',
                        title: 'Support',
                        icon: '<i class="far fa-life-ring"></i>',
                        url: `${BASE_URL}/dashboard/support/`,
                        pos: '199',
                    },
                },
                settings_sub_menu: {
                    store: {
                        menu_key: 'store',
                        is_sortable: 'false',
                        previous_title: 'Store',
                        menu_manager_title: 'Store',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'false',
                        is_switched_on: 'true',
                        menu_manager_position: '0',
                        title: 'Store',
                        icon: '<i class="fas fa-university"></i>',
                        url: `${BASE_URL}/dashboard/settings/store/`,
                        pos: '30',
                        permission: 'dokan_view_store_settings_menu',
                    },
                    'product-addon': {
                        menu_key: 'product-addon',
                        is_sortable: 'true',
                        previous_title: 'Addons',
                        menu_manager_title: 'Addons',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '1',
                        title: 'Addons',
                        icon: '<i class="fas fa-puzzle-piece" aria-hidden="true"></i>',
                        url: `${BASE_URL}/dashboard/settings/product-addon/`,
                        pos: '40',
                    },
                    payment: {
                        menu_key: 'payment',
                        is_sortable: 'true',
                        previous_title: 'Payment',
                        menu_manager_title: 'Payment',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '2',
                        title: 'Payment',
                        icon: '<i class="far fa-credit-card"></i>',
                        url: `${BASE_URL}/dashboard/settings/payment/`,
                        pos: '50',
                        permission: 'dokan_view_store_payment_menu',
                    },
                    verification: {
                        menu_key: 'verification',
                        is_sortable: 'true',
                        previous_title: 'Verification',
                        menu_manager_title: 'Verification',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '3',
                        title: 'Verification',
                        icon: '<i class="fas fa-check"></i>',
                        url: `${BASE_URL}/dashboard/settings/verification/`,
                        pos: '55',
                        permission: 'dokan_view_store_verification_menu',
                    },
                    shipping: {
                        menu_key: 'shipping',
                        is_sortable: 'true',
                        previous_title: 'Shipping',
                        menu_manager_title: 'Shipping',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '4',
                        title: 'Shipping',
                        icon: '<i class="fas fa-truck"></i>',
                        url: `${BASE_URL}/dashboard/settings/shipping/`,
                        pos: '70',
                        permission: 'dokan_view_store_shipping_menu',
                    },
                    shipstation: {
                        menu_key: 'shipstation',
                        is_sortable: 'true',
                        previous_title: 'ShipStation',
                        menu_manager_title: 'ShipStation',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '5',
                        title: 'ShipStation',
                        icon: '<i class="fas fa-cog"></i>',
                        url: `${BASE_URL}/dashboard/settings/shipstation/`,
                        pos: '72',
                        permission: 'dokan_view_store_shipping_menu',
                    },
                    social: {
                        menu_key: 'social',
                        is_sortable: 'true',
                        previous_title: 'Social Profile',
                        menu_manager_title: 'Social Profile',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '6',
                        title: 'Social Profile',
                        icon: '<i class="fas fa-share-alt-square"></i>',
                        url: `${BASE_URL}/dashboard/settings/social/`,
                        pos: '90',
                        permission: 'dokan_view_store_social_menu',
                    },
                    rma: {
                        menu_key: 'rma',
                        is_sortable: 'true',
                        previous_title: 'RMA',
                        menu_manager_title: 'RMA',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '7',
                        title: 'RMA',
                        icon: '<i class="fas fa-undo-alt" aria-hidden="true"></i>',
                        url: `${BASE_URL}/dashboard/settings/rma/`,
                        pos: '93',
                        permission: 'dokan_view_store_rma_menu',
                    },
                    seo: {
                        menu_key: 'seo',
                        is_sortable: 'true',
                        previous_title: 'Store SEO',
                        menu_manager_title: 'Store SEO',
                        edit_now: 'false',
                        editable: 'true',
                        temporary_disable_edit: 'false',
                        switchable: 'true',
                        is_switched_on: 'true',
                        menu_manager_position: '8',
                        title: 'Store SEO',
                        icon: '<i class="fas fa-globe"></i>',
                        url: `${BASE_URL}/dashboard/settings/seo/`,
                        pos: '110',
                        permission: 'dokan_view_store_seo_menu',
                    },
                },
            },
        },
        privacyPolicySettings: {
            enable_privacy: 'on',
            privacy_page: '2',
            privacy_policy: '<p>Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our [dokan_privacy_policy]</p>',
        },

        colorsSettings: {
            store_color_pallete: {
                value: 'default',
                btn_text: '#FFFFFF',
                btn_hover: '#DD3B0F',
                btn_primary: '#F05025',
                dash_nav_bg: '#1B233B',
                dash_nav_text: '#CFCFCF',
                pallete_status: 'template',
                btn_hover_text: '#FFFFFF',
                dash_active_link: '#F05025',
                btn_hover_border: '#C83811',
                btn_primary_border: '#DA502B',
                dash_nav_active_text: '#FFFFFF',
                color_options: {
                    'color-1': '#1B233B',
                    'color-2': '#F05025',
                    'color-3': '#CFCFCF',
                    'color-4': '#DD3B0F',
                },
            },
        },

        liveSearchSettings: {
            live_search_option: 'suggestion_box',
        },

        storeSupportSettings: {
            enabled_for_customer_order: 'on',
            store_support_product_page: 'above_tab',
            support_button_label: 'Get Support',
        },

        sellerVerificationSettings: {
            facebook_app_details: '',
            twitter_app_details: '',
            google_details: '',
            linkedin_details: '',
            fb_app_id: '',
            fb_app_secret: '',
            twitter_app_id: '',
            twitter_app_secret: '',
            google_app_id: '',
            google_app_secret: '',
        },

        verificationSMSGatewaysSettings: {
            sender_name: 'weDevs Team',
            sms_text: 'Your verification code is: %CODE%',
            sms_sent_msg: 'SMS sent. Please enter your verification code',
            sms_sent_error: 'Unable to send sms. Contact admin',
            active_gateway: '',

            // nexmo details
            nexmo_details: '',
            nexmo_username: '',
            nexmo_pass: '',

            // twilio details
            twilio_details: '',
        },

        emailVerificationSettings: {
            enabled: 'off',
            registration_notice: 'Please check your email and complete email verification to login.',
            login_notice: 'Please check your email and complete email verification to login.',
        },

        socialAPISettings: {
            section_title: '',
            enabled: 'on',
            facebook_details: '',
            twitter_details: '',
            google_details: '',
            linkedin_details: '',
            apple_details: '',
            fb_app_id: '',
            fb_app_secret: '',
            twitter_app_id: '',
            twitter_app_secret: '',
        },

        shippingStatusSettings: {
            enabled: 'on',
            shipping_status_provider: {
                'sp-dhl': 'sp-dhl',
                'sp-dpd': 'sp-dpd',
                'sp-fedex': 'sp-fedex',
                'sp-polish-shipping-providers': 'sp-polish-shipping-providers',
                'sp-ups': 'sp-ups',
                'sp-usps': 'sp-usps',
                'sp-other': 'sp-other',
            },
            shipping_status_list: [
                {
                    id: 'ss_delivered',
                    value: 'Delivered',
                    must_use: 'true',
                    desc: '(This is must use item)',
                },
                {
                    id: 'ss_cancelled',
                    value: 'Cancelled',
                    must_use: 'true',
                    desc: '(This is must use item)',
                },
                {
                    id: 'ss_proceccing',
                    value: 'Processing',
                },
                {
                    id: 'ss_ready_for_pickup',
                    value: 'Ready for pickup',
                },
                {
                    id: 'ss_pickedup',
                    value: 'Pickedup',
                },
                {
                    id: 'ss_on_the_way',
                    value: 'On the way',
                },
            ],
        },

        quoteSettings: {
            // quote settings
            dokan_quote_settings: '',
            enable_out_of_stock: 'on',
            enable_ajax_add_to_quote: 'on',
            redirect_to_quote_page: 'off',

            // quote attributes settings
            quote_attributes_settings: '',
            decrease_offered_price: '0',
            enable_convert_to_order: 'off',
            enable_quote_converter_display: 'off',
        },

        liveChatSettings: {
            enable: 'off',
            provider: 'messenger',
            theme_color: '#0084FF',
            app_id: '',
            app_secret: '',
            wa_opening_method: 'in_app',
            wa_pre_filled_message: 'Hello {store_name}, I have an enquiry regarding your store at {store_url}',
            chat_button_seller_page: 'on',
            chat_button_product_page: 'above_tab',
        },

        rmaSettings: {
            rma_order_status: 'wc-processing',
            rma_enable_refund_request: 'on',
            rma_enable_coupon_request: 'on',
            rma_reasons: [
                {
                    id: 'defective',
                    value: 'Defective',
                },
                {
                    id: 'wrong_product',
                    value: 'Wrong Product',
                },
                {
                    id: 'other',
                    value: 'Other',
                },
            ],
            rma_policy: '<p>Refund Policy</p>',
        },

        wholesaleSettings: {
            wholesale_price_display: 'all_user',
            display_price_in_shop_archieve: 'on',
            need_approval_for_wholesale_customer: 'off',
        },

        euComplianceSettings: {
            vendor_fields: {
                dokan_company_name: 'dokan_company_name',
                dokan_company_id_number: 'dokan_company_id_number',
                dokan_vat_number: 'dokan_vat_number',
                dokan_bank_name: 'dokan_bank_name',
                dokan_bank_iban: 'dokan_bank_iban',
            },
            vendor_registration: 'on',
            customer_fields: {
                billing_dokan_company_id_number: 'billing_dokan_company_id_number',
                billing_dokan_vat_number: 'billing_dokan_vat_number',
                billing_dokan_bank_name: 'billing_dokan_bank_name',
                billing_dokan_bank_iban: 'billing_dokan_bank_iban',
            },
            enabled_germanized: 'on',
            override_invoice_number: 'on',
        },

        deliveryTimeSettings: {
            allow_vendor_override_settings: 'on',
            delivery_support: {
                delivery: 'delivery',
                'store-pickup': 'store-pickup',
            },
            delivery_date_label: 'Delivery Date',
            preorder_date: 0,
            time_slot_minutes: 30,
            order_per_slot: 0,
            delivery_box_info: 'This store needs %DAY% day(s) to process your delivery request',
            selection_required: 'off',
            delivery_day: '',
            delivery_day_monday: {
                delivery_status: 'monday',
                opening_time: '12:00 am',
                closing_time: '11:59 pm',
            },
            delivery_day_tuesday: {
                delivery_status: 'tuesday',
                opening_time: '12:00 am',
                closing_time: '11:59 pm',
            },
            delivery_day_wednesday: {
                delivery_status: 'wednesday',
                opening_time: '12:00 am',
                closing_time: '11:59 pm',
            },
            delivery_day_thursday: {
                delivery_status: 'thursday',
                opening_time: '12:00 am',
                closing_time: '11:59 pm',
            },
            delivery_day_friday: {
                delivery_status: 'friday',
                opening_time: '12:00 am',
                closing_time: '11:59 pm',
            },
            delivery_day_saturday: {
                delivery_status: 'saturday',
                opening_time: '12:00 am',
                closing_time: '11:59 pm',
            },
            delivery_day_sunday: {
                delivery_status: 'sunday',
                opening_time: '12:00 am',
                closing_time: '11:59 pm',
            },
        },

        productAdvertisingSettings: {
            total_available_slot: '100',
            expire_after_days: '10',
            per_product_enabled: 'on',
            cost: '20',
            vendor_subscription_enabled: 'on',
            featured: 'on',
            catalog_priority: 'on',
            hide_out_of_stock_items: 'on',
        },

        geolocationSettings: {
            show_locations_map: 'top',
            show_location_map_pages: 'all',
            show_filters_before_locations_map: 'on',
            show_product_location_in_wc_tab: 'on',
            distance_unit: 'km',
            distance_min: '0',
            distance_max: '10',
            map_zoom: '11',
            location: {
                latitude: '40.7127753',
                longitude: '-74.0059728',
                address: 'New York, NY, USA',
                zoom: '10',
            },
        },

        productReportAbuseSettings: {
            reported_by_logged_in_users_only: 'off',
            abuse_reasons: [
                {
                    id: 'report_as_spam',
                    value: 'This content is spam',
                },
                {
                    id: 'report_as_adult',
                    value: 'This content should marked as adult',
                },
                {
                    id: 'report_as_abusive',
                    value: 'This content is abusive',
                },
                {
                    id: 'report_as_violent',
                    value: 'This content is violent',
                },
                {
                    id: 'report_as_risk_of_hurting',
                    value: 'This content suggests the author might be risk of hurting themselves',
                },
                {
                    id: 'report_as_infringes_copyright',
                    value: 'This content infringes upon my copyright',
                },
                {
                    id: 'report_as_contains_private_info',
                    value: 'This content contains my private information',
                },
                {
                    id: 'other',
                    value: 'Other',
                },
                {
                    id: 'this_product_is_fake',
                    value: 'This product is fake',
                },
            ],
        },

        spmvSettings: {
            enable_pricing: 'on',
            sell_item_btn: 'Sell This Item',
            available_vendor_list_title: 'Other Available Vendor',
            available_vendor_list_position: 'below_tabs',
            show_order: 'show_all',
        },

        vendorSubscriptionSettings: {
            subscription_pack: '2',
            enable_pricing: 'off',
            enable_subscription_pack_in_reg: 'off',
            notify_by_email: 'on',
            no_of_days_before_mail: '1',
            product_status_after_end: 'draft',
            cancelling_email_subject: 'Subscription Package Cancel notification',
            cancelling_email_body: 'Dear subscriber, Your subscription has expired. Please renew your package to continue using it.',
            alert_email_subject: 'Subscription Ending Soon',
            alert_email_body: 'Dear subscriber, Your subscription will be ending soon. Please renew your package in a timely',
        },

        // dokan pro license
        dokanProLicense: {
            key: process.env.LICENSE_KEY,
            status: 'activate',
            remaining: 42,
            activation_limit: 50,
            expiry_days: 329,
            title: 'Business',
            source_id: 'dokan-business',
            recurring: 1,
        },

        // dokan pro modules
        modules: [
            'auction',
            'booking',
            'color_scheme_customizer',
            'delivery_time',
            'elementor',
            'export_import',
            'follow_store',
            'geolocation',
            'germanized',
            'live_chat',
            'live_search',
            'mangopay',
            'moip',
            'order_min_max',
            'paypal_marketplace',
            'product_addon',
            'product_advertising',
            'product_enquiry',
            'product_subscription',
            'rank_math',
            'razorpay',
            'report_abuse',
            'request_for_quotation',
            'rma',
            'seller_badge',
            'seller_vacation',
            'shipstation',
            'spmv',
            'store_reviews',
            'store_support',
            'stripe',
            'stripe_express',
            'table_rate_shipping',
            'vendor_analytics',
            'vendor_staff',
            'vendor_verification',
            'vsp',
            'wholesale',
        ],

        // abuse report
        createAbuseReport: {
            reason: 'This content is spam',
            description: 'spam product',
        },
    },

    // wp

    optionName: {
        activePlugins: 'active_plugins',
    },

    plugins: {
        '0': 'Basic-Auth-master/basic-auth.php',
        // '1':'woocommerce/woocommerce.php',
        // '2':'dokan/dokan.php',
        // '3':'dokan-pro/dokan-pro.php',
        // '4':'woocommerce-bookings/woocommerce-bookings.php',
        // '5':'woocommerce-product-addons/woocommerce-product-addons.php',
        // '6':'woocommerce-simple-auctions/woocommerce-simple-auctions.php',
        // '7':'woocommerce-subscriptions/woocommerce-subscriptions.php'
        // curl --user admin:01dokan01 http://dokan5.test/wp-json
        // curl --user admin:01dokan01 http://dokan5.test/wp-json/wp/v2/plugins
    },

    siteSettings: {
        users_can_register: 1,
        start_of_week: 1,
        date_format: 'F j, Y',
        time_format: 'g:i a',
        permalink_structure: '/%postname%/',
        default_role: 'subscriber',
        timezone_string: 'Asia/Dhaka',
    },

    // woocommerce

    woocommerceSettings: {
        woocommerce_enable_myaccount_registration: 'yes',
    },

    // test db data

    testData: {
        dokan: {
            generalSettings: {
                // site settings
                site_options: '',
                admin_access: 'on', // vendor edit product test needs it to disable
                custom_store_url: 'stores',
                setup_wizard_logo_url: '',
                setup_wizard_message:
                    '<p>Thank you for choosing The Marketplace to power your online store! This quick setup wizard will help you configure the basic settings. <strong>It&rsquo;s completely optional and shouldn&rsquo;t take longer than two minutes.</strong> Test wizard message.</p>',
                setup_wizard_message_without_html:
                    'Thank you for choosing The Marketplace to power your online store! This quick setup wizard will help you configure the basic settings. It’s completely optional and shouldn’t take longer than two minutes. Test wizard message.',
                disable_welcome_wizard: 'off',
                global_digital_mode: 'sell_both',
                enable_shipstation_logging: 'off',
                data_clear_on_uninstall: 'off',

                // vendor store settings
                vendor_store_options: '',
                seller_enable_terms_and_conditions: 'on',
                store_products_per_page: '12',
                enabled_address_on_reg: 'off',
                enable_tc_on_reg: 'on',
                enable_single_seller_mode: 'off',
                store_category_type: 'multiple', // none, multiple

                // product page settings
                product_page_options: '',
                show_vendor_info: 'on',
                enabled_more_products_tab: 'on',
            },
        },
    },
};
