Feature('explore Backend Functionality');

Scenario('test something', ({ I }) => {
    I.loginAsAdmin();
I.amOnPage('/wp-admin');
I.click('Dokan');
    I.waitForElement('.widgets-wrapper');
    I.checkError();
    I.see('At a Glance');
    I.see('Overview');
    I.see('Dokan News Updates');
    I.click('Modules');
           // I.waitForElement('.module-content');
           // checkError();
            // I.seeElement('.displaying-num','26 items');
        // Activate all modules
    I.click('#view-switch-list');
    I.wait(5);
    I.click('//input[@type="checkbox"]');
    I.selectOption('#bulk-action-selector-top','Activate');
    I.click('Apply');
    I.wait(5);
I.click('Withdraw');
    I.waitForElement('.withdraw-requests');
    I.checkError();
    
        
    	    I.click('Abuse Reports');
            I.waitForElement('#vue-backend-app');
            I.checkError();
            // I.seeElement('//div[@class="tablenav top"]');
    	   I.amOnPage('/wp-admin/admin.php?page=dokan#/store-reviews');
    	// I.click('//li[@id="toplevel_page_dokan"]/ul/li[6]/a','Store Reviews');
    	// I.waitForElement('.dokan-store-reviews');
            I.waitForElement('.dokan-store-reviews');
            I.checkError();
    	I.click('Announcements');
            I.waitForElement('.dokan-announcement-wrapper');
            I.checkError();
    	I.click('Refunds');
            I.waitForElement('.dokan-refund-wrapper');
            I.checkError();
    	I.click('Reports');
            I.waitForElement('#vue-backend-app');
            I.checkError();
            I.click('All Logs');
                I.waitForElement('#vue-backend-app');
                I.checkError();
    	I.click('Tools');
            I.waitForElement('.tools-page');
            I.checkError();
    	// I.click('Subscriptions');
      //       I.waitForElement('.subscription-list');
      //       checkError();
    	I.click('Verifications');
            I.waitForElement('#wpbody-content');
            I.checkError();
    	I.click('Wholesale Customer');
           // I.waitForElement('.wholesale-customer-list');
            I.checkError();
    	I.click('Help');
            I.waitForElement('#wpbody-content');
            I.checkError();
        // I.amOnPage('/wp-admin/admin.php?page=dokan#/settings');
    	I.click('Settings');
            // I.waitForElement('#dokan_general');
            I.checkError();
            // I.click('Save Changes');
            // I.waitForElement('#setting-message_updated', 5);
    	I.click('Selling Options');
        I.waitForElement('#dokan_selling');
        I.checkError();
            // I.click('Save Changes'); 
            // I.waitForElement('#setting-message_updated', 5);
    	I.click('Withdraw Options');
            I.waitForElement('#dokan_withdraw');
            I.checkError();
            // I.click('Save Changes');
            // I.waitForElement('#setting-message_updated', 5);
    	I.click('Page Settings');
        I.waitForElement('#dokan_pages');
        I.checkError();
        I.click('//a[5]');
            I.waitForElement('#dokan_appearance');
            I.checkError();
        I.click('Privacy Policy');
            I.waitForElement('#dokan_privacy');
            I.checkError();
        I.click('Seller Verification');
            I.waitForElement('#dokan_verification');
            I.checkError();
        I.click('Verification SMS Gateways');
            I.waitForElement('#dokan_verification_sms_gateways');
            I.checkError();
        I.click('Colors');
            I.waitForElement('#dokan_colors');
            I.checkError();
        I.click('Email Verification');
            I.waitForElement('#dokan_email_verification');
            I.checkError();
        I.click('Social API');
            I.waitForElement('#dokan_social_api');
            I.checkError();        
        // I.click('Live Chat');
        //     I.waitForElement('#dokan_live_chat');
        //     I.checkError();
        I.click('RMA');
            I.waitForElement('#dokan_rma');
            I.checkError();
        I.click('Wholesale');
            I.waitForElement('#dokan_wholesale');
            I.checkError();
        I.click('Geolocation');
            I.waitForElement('#dokan_geolocation');
            I.checkError();
        I.click('Product Report Abuse');
            I.waitForElement('#dokan_report_abuse');
            I.checkError();
        I.click('Single Product MultiVendor');
            I.waitForElement('#dokan_spmv');
            I.checkError();
        // I.click('Product Subscription');
        //     I.waitForElement('#dokan_product_subscription');
        //     I.checkError();
        /*I.click('Vendor Analytics');
            I.waitForElement('#dokan_vendor_analytics');
            checkError();*/
           I.amOnPage('/wp-admin/admin.php?page=dokan#/settings');
        //     I.click('(//a[contains(text(),"General")])[2]');
            // I.scrollPageToTop();
            // I.click('General');
            I.click('(//a[contains(text(),"General")])[2]');
            I.selectOption('dokan_general[store_category_type]','multiple');
            I.click('Save Changes');
            I.see('Setting has been saved successfully.');
            I.amOnPage('/wp-admin/admin.php?page=dokan#/vendors/');
            // I.see('Store Categories');
            I.amOnPage('/wp-admin/admin.php?page=dokan#/vendors/');
            //I.click('Vendors');
            I.waitForElement('.vendor-list');
            I.checkError();
            I.see('Add New');
            I.seeElement('#post-search-input');
            I.see('Bulk Actions')
            I.see('s');
            I.wait(5);
            I.amOnPage('/wp-admin/admin.php?page=dokan#/settings');
            I.click('Withdraw Options');
            // I.checkOption('PayPal');
            I.checkOption('Bank Transfer');
            I.checkOption('dokan_withdraw[withdraw_order_status][wc-completed]');
            I.click('Save Changes');
            I.see('Setting has been saved successfully.');
            I.checkError();
            I.amOnPage('/wp-admin/admin.php?page=dokan#/withdraw?status=pending');
            //I.click('Withdraw');
            I.seeElement({css: '.subsubsub > li:nth-child(2) > a'});
            I.seeElement({css:'.subsubsub > li:nth-child(3) > a'});
            I.seeElement({"css":".top #bulk-action-selector-top"});
            I.click('Abuse Reports');
            I.seeElement({"css":".top #bulk-action-selector-top"});
            I.seeElement({"css":"select:nth-child(1)"});
            I.seeElement({"css":"#select2-filter-products-container > .select2-selection__placeholder"});
            I.seeElement({"css":"#select2-filter-vendors-container > .select2-selection__placeholder"});
            I.click("Store Reviews");
            I.seeElement({"css":".top #bulk-action-selector-top"});
            I.seeElement( "//span[@id='select2-filter-vendors-container']/span");
            I.click("Announcements");
            I.seeElement("//a[contains(text(),'Add Announcement')]");
            I.seeElement("//a[contains(@href, '#/announcement?status=publish')]");
            I.seeElement("//a[contains(@href, '#/announcement?status=pending')]");
            I.seeElement("//a[contains(@href, '#/announcement?status=future')]");
            I.seeElement("//a[contains(@href, '#/announcement?status=future')]");
            I.seeElement("//a[contains(@href, '#/announcement?status=draft')]");
            I.seeElement("//a[contains(@href, '#/announcement?status=trash')]");
            I.seeElement({"css":".top #bulk-action-selector-top"});
            I.click("Refunds");
            I.seeElement("(//a[contains(@href, '#/refund?status=pending')])[2]");
            I.seeElement("//a[contains(@href, '#/refund?status=completed')]");
            I.seeElement("//a[contains(@href, '#/refund?status=cancelled')]");
            I.seeElement({"css":".top #bulk-action-selector-top"});
            I.click('Reports');
            I.click("By Day");
            I.click("By Year");
            I.click("By Vendor");
            I.seeElement("//input");
            I.seeElement({"css":".button"});
            I.click("All Logs");
            I.seeElement("//span[@id='select2-filter-vendors-container']");
            I.seeElement("//span[@id='select2-filter-status-container']");
            I.seeElement("//input[@id='post-search-input']");
            I.click("Tools");
            I.seeElement("//a[contains(text(),'Dashboard')]");
            I.seeElement("//a[contains(text(),'Re-build')]");
            I.seeElement("//a[contains(text(),'Check Orders')]");
        // I.click("Subscriptions");
        //     I.seeElement({"css":".top #bulk-action-selector-top"});
            I.click("Wholesale Customer");
            I.seeElement({"css":".top #bulk-action-selector-top"});
            I.seeElement("//a[contains(@href, '#/wholesale-customer?status=all')]");
            I.seeElement("//a[contains(@href, '#/wholesale-customer?status=active')]");
            I.seeElement("//a[contains(@href, '#/wholesale-customer?status=deactive')]");
            // I.click("Updates");
            I.click("Settings");
            I.click("//a[contains(text(),'Appearance')]");
            I.checkOption("//input[@id='dokan_appearance[store_map]']");
            I.checkOption("google_maps");
            I.click("Save Changes");
            I.click("Colors");
            I.click("Save Changes");
            I.click("RMA");
            I.selectOption("//select[@id='dokan_rma[rma_order_status]']","Completed");
            I.selectOption("//select[@id='dokan_rma[rma_enable_refund_request]']","yes");
            I.click("Save Changes");
            I.click("Wholesale");
            I.checkOption("//input[@id='dokan_wholesale[wholesale_price_display][wholesale_customer]']");
            I.selectOption("//select[@id='dokan_wholesale[need_approval_for_wholesale_customer]']","Yes");
            I.click("Save Changes");
            // I.click("Live Chat");
            //     I.checkOption("dokan_live_chat[enable]");
            //     I.checkOption("//input[@id='dokan_live_chat[provider][talkjs]']");
            //     I.fillField("//input[@id='dokan_live_chat[app_id]']","tmHBI9mp");
            //     I.fillField("//input[@id='dokan_live_chat[app_secret]']","sk_test_mNpaPINePWDXn5jMeDNavH9b");
            //     I.click("Save Changes");
            I.click("Product Report Abuse");
            I.checkOption('//div[@id="dokan_report_abuse"]/form/table/tbody/tr/td/fieldset/label')
           // I.checkOption({"css":".reported_by_logged_in_users_only > td"});
            I.click("Save Changes");
            I.click("Geolocation");
            I.fillField("//div[@id='dokan_geolocation']/form/table/tbody/tr[8]/td/div/input","Dhaka");
            I.click("Save Changes");
           // I.wait(4);
            //I.amOnPage('/wp-admin/admin.php?page=dokan#/settings/');
            //I.click({css:'.nav-tab-active'});
           // I.click({ link: '[General]'});


});
