//TODO: #  // "no-unused-vars": "off" is enabled for now but remove before push
//TODO: # Configure projects for multiple environments : ci, local,
//TODO: # convert waitForNavigation to waitForUrl
//TODO: # why two pages are oppening : fix that
//TODO: # test should run parallely
//TODO: # add fixture
//TODO: use extrahttpheaders: for grab storage.json  // not possible
//TODO: usr extrahttpheaders: for test describe and avoid storage.json all-together
//TODO: convert all expect parameter to correct way: left side received and right part expected
//TODO: convert all string assertion:
// filter received & expected test
// trim if necessary
// lowercase
