import { Page, expect, request as apiRequest } from '@playwright/test';
import type { APIRequestContext } from '@playwright/test';
import { toPath, closeAnnouncementModal, parseBoolean } from '@utils/helpers';
import { ApiUtils as DokanApiUtils } from '@utils/apiUtils';
import { data } from '@utils/testData';

// Re-export the REAL utils so the spec's import contract
// `{ ShortcodePage, ApiUtils, data, payloads, dbUtils, dbData }` resolves to
// real functionality (no local no-op stubs).
export { data };
export { payloads } from '@utils/payloads';
export { dbUtils } from '@utils/dbUtils';
export { dbData } from '@utils/dbData';

// Pro-only surfaces (EU-compliance fields, geolocation map, follow button, …) are
// gated on DOKAN_PRO. parseBoolean guards against the string-"false" truthiness trap.
const DOKAN_PRO = parseBoolean(process.env.DOKAN_PRO);

/**
 * ApiUtils — thin wrapper over the REAL `@utils/apiUtils` ApiUtils.
 *
 * The spec constructs this as `new ApiUtils(null)` (it owns no request fixture),
 * so when no APIRequestContext is supplied we lazily provision one via
 * Playwright's `request.newContext()`. Every method delegates to the real
 * ApiUtils, i.e. real REST calls — this is not a stub.
 */
export class ApiUtils {
    private impl: DokanApiUtils | null;
    private ownedContext: APIRequestContext | null = null;

    constructor(request?: APIRequestContext | null) {
        this.impl = request ? new DokanApiUtils(request) : null;
    }

    private async utils(): Promise<DokanApiUtils> {
        if (!this.impl) {
            this.ownedContext = await apiRequest.newContext();
            this.impl = new DokanApiUtils(this.ownedContext);
        }
        return this.impl;
    }

    async createPage(payload: any, auth?: any): Promise<[any, string]> {
        return (await this.utils()).createPage(payload, auth);
    }

    async deletePage(pageId: string, auth?: any): Promise<any> {
        return (await this.utils()).deletePage(pageId, auth);
    }

    async createProductAdvertisement(product: object, auth?: any): Promise<any> {
        return (await this.utils()).createProductAdvertisement(product, auth);
    }

    async dispose(): Promise<void> {
        if (this.ownedContext) {
            await this.ownedContext.dispose();
            this.ownedContext = null;
        } else if (this.impl) {
            await this.impl.dispose();
        }
    }
}

// Co-located selectors ported verbatim from the pre-refactor selectors.ts groups
// (admin.pages, vendor.vRegistration, vendor.vSubscriptions, vendor.vDashboard,
//  customer.cShop, customer.cDashboard, customer.cStoreList, customer.cMyOrders,
//  customer.cRequestForQuote).
export const shortcodesSelectors = {
    // admin → new page (block editor)
    adminPages: {
        blockEditorModal: '//div[@aria-label="Welcome to the block editor"]',
        closeModal: 'div.components-modal__content button[aria-label="Close"]',
        addTitle: 'h1.wp-block-post-title',
        contentPlaceholder: 'p[aria-label="Add default block"]',
        addContent: '//p[@data-title="Paragraph"]',
        publish: '//div[@class="editor-header__settings"]//button[text()="Publish"]',
        publishFromPanel: '//div[@class="editor-post-publish-panel"]//button[text()="Publish"]',
        publishMessage: '//div[@class="components-snackbar__content" and text()="Page published."]',
    },

    // vendor registration form ([dokan-vendor-registration] / onboarding)
    vendorRegistration: {
        regEmail: 'input#reg_email',
        regPassword: 'input#reg_password',
        firstName: 'input#first-name',
        lastName: 'input#last-name',
        shopName: 'input#company-name',
        shopUrl: 'input#seller-url',
        phone: 'input#shop-phone',
        companyName: 'input#dokan-company-name',
        companyId: 'input#dokan-company-id-number',
        vatNumber: 'input#dokan-vat-number',
        bankName: 'input#dokan-bank-name',
        bankIban: 'input#dokan-bank-iban',
        // button shows only on the dokan registration form generated by the shortcode
        registerDokanButton: 'input[name="register"]',
    },

    // customer migration form ([dokan-customer-migration])
    customerMigration: {
        firstName: '#first-name',
        lastName: '#last-name',
        shopName: '#company-name',
        shopUrl: '#seller-url',
        phone: '#shop-phone',
        companyName: '#dokan-company-name',
        companyId: '#dokan-company-id-number',
        vatNumber: '#dokan-vat-number',
        bankName: '#dokan-bank-name',
        bankIban: '#dokan-bank-iban',
        becomeAVendor: '.dokan-btn',
    },

    // storefront shop / geolocation filter + product cards ([dokan-geolocation-filter-form],
    // [dokan-best-selling-product], [dokan-top-rated-product], [dokan_product_advertisement])
    shop: {
        filters: {
            filterDiv: 'form.dokan-geolocation-location-filters',
            searchProduct: 'input.dokan-form-control[placeholder="Search Products"]',
            location: '.location-address input',
            selectCategory: '#dokan-geo-product-categories-root',
            radiusSlider: '.dokan-range-slider',
            search: '.dokan-btn',
        },
        productCard: {
            card: '#main ul.products li',
            productDetailsLink: '#main ul.products li.product a.woocommerce-LoopProduct-link',
            productTitle: '#main .products .woocommerce-loop-product__title',
            productPrice: '#main .products .price',
            addToCart: '#main .products a.add_to_cart_button',
        },
    },

    // vendor subscription packs ([dps_product_pack])
    vendorSubscriptions: {
        dokanSubscriptionDiv: 'div.dokan-subscription-content',
        noSubscriptionMessage: '//h3[text()="No subscription pack has been found!"]',
        sellerSubscriptionInfo: 'div.seller_subs_info',
        productCardContainer: 'div.pack_content_wrapper',
        productCard: {
            item: 'div.product_pack_item',
            price: 'div.pack_price',
            content: 'div.pack_content',
            buyButton: 'div.buy_pack_button',
        },
    },

    // vendor dashboard ([dokan-dashboard])
    vendorDashboard: {
        reactRoot: '#dokan-vendor-dashboard-root',
        reactSpinner: '#dokan-vendor-dashboard-root .animate-spin',
        dashboardWrap: '.dokan-dashboard-wrap',
        dashboardContent: '.dokan-dashboard-content',
        bigCounter: '.dashboard-widget.big-counter',
        atAGlance: {
            atAGlanceDiv: '.dashboard-widget.big-counter',
            netSalesTitle: '//div[normalize-space()="Net Sales"]',
            earningTitle: '//div[normalize-space()="Earning"]',
            pageviewTitle: '//div[normalize-space()="Pageview"]',
            orderTitle: '//div[normalize-space()="Order"]',
            salesValue: '//div[@class="title" and contains(text(), "Net Sales")]/..//div[@class="count"]',
            earningValue: '//div[@class="title" and contains(text(), "Earning")]/..//div[@class="count"]',
            pageViewValue: '//div[@class="title" and contains(text(), "Pageview")]/..//div[@class="count"]',
            orderValue: '//div[@class="title" and contains(text(), "Order")]/..//div[@class="count"]',
        },
        graph: {
            graphDiv: '.dashboard-widget.sells-graph',
            widgetTitle: '.sells-graph .widget-title',
            chart: '.chart-container',
        },
        orders: {
            ordersDiv: '.dashboard-widget.orders',
            widgetTitle: '.orders .widget-title',
            totalTitle: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Total"]',
            completedTitle: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Completed"]',
            pendingTitle: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Pending"]',
            processingTitle: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Processing"]',
            cancelledTitle: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Cancelled"]',
            refundedTitle: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Refunded"]',
            onholdTitle: '//div[@class="dashboard-widget orders"]//span[normalize-space()="On hold"]',
            totalValue: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Total"]/..//span[@class="count"]',
            completedValue: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Completed"]/..//span[@class="count"]',
            pendingValue: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Pending"]/..//span[@class="count"]',
            processingValue: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Processing"]/..//span[@class="count"]',
            cancelledValue: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Cancelled"]/..//span[@class="count"]',
            refundedValue: '//div[@class="dashboard-widget orders"]//span[normalize-space()="Refunded"]/..//span[@class="count"]',
            onholdValue: '//div[@class="dashboard-widget orders"]//span[normalize-space()="On hold"]/..//span[@class="count"]',
            pieChart: '#order-stats',
        },
        products: {
            productsDiv: '.dashboard-widget.products',
            addNewProduct: '//a[contains(normalize-space(.), "Add new product")]',
            widgetTitle: '.products .widget-title',
            totalTitle: '//div[@class="dashboard-widget products"]//span[normalize-space()="Total"]',
            liveTitle: '//div[@class="dashboard-widget products"]//span[normalize-space()="Live"]',
            offlineTitle: '//div[@class="dashboard-widget products"]//span[normalize-space()="Offline"]',
            pendingReviewTitle: '//div[@class="dashboard-widget products"]//span[normalize-space()="Pending Review"]',
            totalValue: '//div[@class="dashboard-widget products"]//span[normalize-space()="Total"]/..//span[@class="count"]',
            liveValue: '//div[@class="dashboard-widget products"]//span[normalize-space()="Live"]/..//span[@class="count"]',
            offlineValue: '//div[@class="dashboard-widget products"]//span[normalize-space()="Offline"]/..//span[@class="count"]',
            pendingReviewValue: '//div[@class="dashboard-widget products"]//span[normalize-space()="Pending Review"]/..//span[@class="count"]',
        },
        profileProgress: {
            profileProgressDiv: '.dokan-profile-completeness',
            dokanProgressBar: '.dokan-progress',
            dokanProgressBarText: '.dokan-progress-bar',
            nextStep: '.dokan-alert.dokan-alert-info.dokan-panel-alert',
        },
        reviews: {
            reviewsDiv: '.dashboard-widget.reviews',
            widgetTitle: '.reviews .widget-title',
            allTitle: '//div[@class="dashboard-widget reviews"]//span[normalize-space()="All"]',
            pendingTitle: '//div[@class="dashboard-widget reviews"]//span[normalize-space()="Pending"]',
            spamTitle: '//div[@class="dashboard-widget reviews"]//span[normalize-space()="Spam"]',
            trashTitle: '//div[@class="dashboard-widget reviews"]//span[normalize-space()="Trash"]',
            allValue: '//div[@class="dashboard-widget reviews"]//span[normalize-space()="All"]/..//span[@class="count"]',
            pendingValue: '//div[@class="dashboard-widget reviews"]//span[normalize-space()="Pending"]/..//span[@class="count"]',
            spamValue: '//div[@class="dashboard-widget reviews"]//span[normalize-space()="Spam"]/..//span[@class="count"]',
            trashValue: '//div[@class="dashboard-widget reviews"]//span[normalize-space()="Trash"]/..//span[@class="count"]',
        },
        announcement: {
            announcementDiv: '.dashboard-widget.dokan-announcement-widget',
            widgetTitle: '.dokan-announcement-widget .widget-title',
            seeAll: '//a[normalize-space()="See All"]',
        },
    },

    // store listing ([dokan-stores])
    storeList: {
        storeListText: '//h1[normalize-space()="Store List"]',
        map: {
            locationMap: 'div#dokan-geolocation-locations-map',
            map: '//button[normalize-space()="Map"]',
            satellite: '//button[normalize-space()="Satellite"]',
            fullScreenToggle: '//button[@title="Toggle fullscreen view"]',
            pegman: '//button[@title="Drag Pegman onto the map to open Street View"]',
            mapCameraControls: '//button[@title="Map camera controls"]',
            storeOnMap: {
                storePin: '//div[@id="dokan-geolocation-locations-map"]//img[contains(@src, "maps.gstatic.com/mapfiles/transparent.png")]/../..//div[@role="button"]',
                storeCluster: '//div[@id="dokan-geolocation-locations-map"]//div[contains(@style, "dokan-pro/modules/geolocation/assets/images")]',
                storeOnMap: '//span[normalize-space()="To navigate, press the arrow keys."]/..//div',
                storePopup: '.dokan-geo-map-info-window',
                storeListPopup: '.dokan-geo-map-info-windows-in-popup',
                closePopup: 'button.icon-close',
            },
        },
        filters: {
            filterDiv: 'div#dokan-store-listing-filter-wrap',
            totalStoreCount: 'p.item.store-count',
            filterButton: 'button.dokan-store-list-filter-button',
            sortBy: '#stores_orderby',
            gridView: '.dashicons-screenoptions',
            listView: '.dashicons-menu-alt',
            filterDetails: {
                searchVendor: '.store-search-input',
                location: '.location-address input',
                radiusSlider: 'input.dokan-range-slider',
                categoryInput: '.category-input',
                featured: '#featured',
                openNow: '#open-now',
                ratings: '.store-ratings.item',
                rating: (star: string) => `.star-${star}`,
                apply: '#apply-filter-btn',
            },
        },
        storeCard: {
            storeCardDiv: 'div.store-wrapper',
            storeCardHeader: 'div.store-header',
            storeBanner: 'div.store-banner',
            storeCardContent: 'div.store-content',
            storeData: 'div.store-data',
            storeCardFooter: 'div.store-footer',
            storeAvatar: 'div.seller-avatar',
            visitStore: 'a[title="Visit Store"]',
            followUnFollowButton: 'button.dokan-follow-store-button',
        },
    },

    // my orders ([dokan-my-orders])
    myOrders: {
        myOrdersText: '//h1[normalize-space()="My Orders"]',
        recentOrdersText: '//h2[normalize-space()="Recent Orders"]',
        noOrdersFound: 'p.dokan-info',
        table: {
            myOrdersTable: '.shop_table.my_account_orders.table',
            orderColumn: 'th.order-number',
            dateColumn: 'th.order-date',
            statusColumn: 'th.order-status',
            totalColumn: '//span[normalize-space()="Total"]/..',
            vendorColumn: '//span[normalize-space()="Vendor"]/..',
            actionsColumn: 'th.order-actions',
        },
    },

    // request for quote ([dokan-request-quote])
    requestForQuote: {
        requestForQuoteText: '//h1[normalize-space()="Request for Quote"]',
        noQuotesFound: '//p[@class="cart-empty"]',
        returnToShop: '//a[normalize-space()="Return To Shop"]',
        quoteItemDetailsTable: {
            quoteDetailsTable: '//table[contains(@class,"quote_details") and contains(@class,"cart")]',
            productColumn: '//th[@class="product-name"]',
            priceColumn: '//th[normalize-space()="Price"]',
            offeredPriceColumn: '//th[normalize-space()="Offered Price"]',
            quantityColumn: '//th[@class="product-quantity"]',
            subtotalColumn: '//th[normalize-space()="Subtotal"]',
            offeredSubtotalColumn: '//th[normalize-space()="Offered Subtotal"]',
        },
        quoteTotals: {
            quoteTotalsTitle: '//h2[normalize-space()="Quote totals"]',
            quoteTotalsDiv: '.cart_totals',
            quoteTotalsTable: '//div[@class="cart_totals"]//table[contains(@class,"table_quote_totals")]',
            subTotalText: '//tr[@class="cart-subtotal"]',
            offeredPriceSubtotalText: '//tr[@class="cart-subtotal offered"]//th',
            subTotalValue: '//td[@data-title="Subtotal (standard)"]',
            offeredPriceSubtotalValue: '//td[@data-title="Offered Price Subtotal"]',
        },
        updateQuote: 'button#dokan_update_quote_btn',
    },
} as const;

export class ShortcodePage {
    readonly page: Page;

    constructor(page: Page) {
        this.page = page;
        void closeAnnouncementModal(page);
    }

    // ---- raw helpers (ports of the removed basePage helpers) ----

    // toBeVisible(selector)
    private async toBeVisible(selector: string, options?: { timeout?: number }): Promise<void> {
        await expect(this.page.locator(selector)).toBeVisible(options);
    }

    // toContainText(selector, text)
    private async toContainText(selector: string, text: string | RegExp): Promise<void> {
        await expect(this.page.locator(selector)).toContainText(text);
    }

    // notToHaveCount(selector, count)
    private async notToHaveCount(selector: string, count: number): Promise<void> {
        await expect(this.page.locator(selector)).not.toHaveCount(count);
    }

    // isVisible(selector) — short polling probe (basePage default 2s) used for branching.
    private async isVisible(selector: string, timeoutSec = 2): Promise<boolean> {
        const deadline = Date.now() + timeoutSec * 1000;
        do {
            try {
                if (await this.page.locator(selector).first().isVisible()) return true;
            } catch {
                /* empty */
            }
            await this.page.waitForTimeout(100);
        } while (Date.now() < deadline);
        return false;
    }

    // getElementCount(selector)
    private async getElementCount(selector: string): Promise<number> {
        return await this.page.locator(selector).count();
    }

    // multipleElementVisible(selectorsObject) — recurse objects, skip functions, assert strings.
    private async multipleElementVisible(selectors: Record<string, unknown>): Promise<void> {
        for (const key in selectors) {
            const value = selectors[key];
            if (typeof value === 'function') {
                continue;
            } else if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
                await this.multipleElementVisible(value as Record<string, unknown>);
            } else if (typeof value === 'string') {
                await this.toBeVisible(value);
            }
        }
    }

    // close block editor welcome modal (if present)
    async closeBlockEditorModal(): Promise<void> {
        try {
            await expect(this.page.locator(shortcodesSelectors.adminPages.blockEditorModal)).toBeVisible({ timeout: 5000 });
            await this.page.locator(shortcodesSelectors.adminPages.closeModal).click();
            console.log('Modal is visible');
        } catch (error) {
            /* empty */
        }
    }

    // create a page with a dokan shortcode
    async createPageWithShortcode(pageTitle: string, shortcode: string): Promise<void> {
        const pages = shortcodesSelectors.adminPages;
        await this.page.goto(toPath(data.subUrls.backend.addNewPage), { waitUntil: 'domcontentloaded' });
        await this.closeBlockEditorModal();

        await this.page.locator(pages.addTitle).click();
        await this.page.locator(pages.addTitle).pressSequentially(pageTitle, { delay: 100 });
        await this.page.locator(pages.contentPlaceholder).click();
        await this.page.locator(pages.addContent).fill(shortcode);

        await this.page.locator(pages.publish).click();
        await Promise.all([this.page.waitForResponse(response => response.url().includes(data.subUrls.api.wp.pages)), this.page.locator(pages.publishFromPanel).click()]);
        await this.toBeVisible(pages.publishMessage);
    }

    // view dashboard ([dokan-dashboard])
    async viewDashboard(link: string): Promise<void> {
        const dashboard = shortcodesSelectors.vendorDashboard;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        // Detect whether the React vendor dashboard or the legacy widget dashboard rendered.
        const isNewDashboard = await this.isVisible(dashboard.reactRoot);
        const hasTraditionalWidgets = await this.isVisible(dashboard.bigCounter);
        console.log(`Dashboard detection: React=${isNewDashboard}, Traditional=${hasTraditionalWidgets}`);

        if (isNewDashboard) {
            await this.toBeVisible(dashboard.reactRoot);
            // wait for the React dashboard spinner to disappear
            try {
                await this.page.waitForFunction(() => !document.querySelector('#dokan-vendor-dashboard-root .animate-spin'), { timeout: 15000 });
            } catch (error) {
                console.log('React dashboard spinner still present, continuing with basic checks');
            }
            await this.toBeVisible(dashboard.dashboardWrap);
            await this.toBeVisible(dashboard.dashboardContent);
        } else if (hasTraditionalWidgets) {
            await this.multipleElementVisible(dashboard.atAGlance);
            await this.multipleElementVisible(dashboard.graph);
            await this.multipleElementVisible(dashboard.orders);
            await this.multipleElementVisible(dashboard.products);

            if (DOKAN_PRO) {
                await this.multipleElementVisible(dashboard.profileProgress);
                await this.multipleElementVisible(dashboard.reviews);
                await this.multipleElementVisible(dashboard.announcement);
            }
        } else {
            console.log('No traditional widgets detected, assuming React dashboard');
            await this.toBeVisible(dashboard.dashboardWrap);
            await this.toBeVisible(dashboard.dashboardContent);
        }
    }

    // view dokan subscription packs ([dps_product_pack])
    async viewDokanSubscriptionPacks(link: string): Promise<void> {
        const subscriptions = shortcodesSelectors.vendorSubscriptions;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        // subscribed pack info
        const hasSubscription = await this.isVisible(subscriptions.sellerSubscriptionInfo);
        if (!hasSubscription) {
            console.log('No subscribed pack found!');
        } else {
            await this.toBeVisible(subscriptions.sellerSubscriptionInfo);
        }

        // subscription pack list
        const noSubscriptionPacks = await this.isVisible(subscriptions.noSubscriptionMessage);
        if (noSubscriptionPacks) {
            await this.toContainText(subscriptions.noSubscriptionMessage, 'No subscription pack has been found!');
            console.log('No subscription pack found!');
        } else {
            await this.toBeVisible(subscriptions.dokanSubscriptionDiv);
            await this.toBeVisible(subscriptions.productCardContainer);

            await this.notToHaveCount(subscriptions.productCard.item, 0);
            await this.notToHaveCount(subscriptions.productCard.price, 0);
            await this.notToHaveCount(subscriptions.productCard.content, 0);
            await this.notToHaveCount(subscriptions.productCard.buyButton, 0);
        }
    }

    // view vendor registration form ([dokan-vendor-registration])
    async viewVendorRegistrationForm(link: string): Promise<void> {
        const registration = shortcodesSelectors.vendorRegistration;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        await this.toBeVisible(registration.firstName);
        await this.toBeVisible(registration.lastName);
        await this.toBeVisible(registration.regEmail);
        await this.toBeVisible(registration.phone);
        await this.toBeVisible(registration.regPassword);
        await this.toBeVisible(registration.shopName);
        await this.toBeVisible(registration.shopUrl);

        // eu compliance fields
        if (DOKAN_PRO) {
            await this.toBeVisible(registration.companyName);
            await this.toBeVisible(registration.companyId);
            await this.toBeVisible(registration.vatNumber);
            await this.toBeVisible(registration.bankName);
            await this.toBeVisible(registration.bankIban);
        }
        await this.toBeVisible(registration.registerDokanButton);
    }

    // view vendor onboarding registration form ([dokan-vendor-onboarding-registration], Dokan 5.0.0+)
    async viewVendorOnboardingForm(link: string): Promise<void> {
        const registration = shortcodesSelectors.vendorRegistration;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        // The onboarding registration form reuses the vendor-registration field ids.
        await this.toBeVisible(registration.firstName);
        await this.toBeVisible(registration.lastName);
        await this.toBeVisible(registration.regEmail);
        await this.toBeVisible(registration.phone);
        await this.toBeVisible(registration.shopName);
        await this.toBeVisible(registration.shopUrl);
        await this.toBeVisible(registration.registerDokanButton);
    }

    // view best selling / top rated / advertised products
    async viewProducts(link: string): Promise<void> {
        const productCard = shortcodesSelectors.shop.productCard;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        const productCount = await this.getElementCount(productCard.card);
        if (productCount) {
            // product card elements are visible
            await this.notToHaveCount(productCard.card, 0);
            await this.notToHaveCount(productCard.productDetailsLink, 0);
            await this.notToHaveCount(productCard.productTitle, 0);
            await this.notToHaveCount(productCard.productPrice, 0);
            await this.notToHaveCount(productCard.addToCart, 0);
        }
    }

    // view customer migration form ([dokan-customer-migration])
    async viewMigrationForm(link: string): Promise<void> {
        const migration = shortcodesSelectors.customerMigration;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        await this.toBeVisible(migration.firstName);
        await this.toBeVisible(migration.lastName);
        await this.toBeVisible(migration.shopName);
        await this.toBeVisible(migration.shopUrl);
        await this.toBeVisible(migration.phone);

        if (DOKAN_PRO) {
            await this.toBeVisible(migration.companyName);
            await this.toBeVisible(migration.companyId);
            await this.toBeVisible(migration.vatNumber);
            await this.toBeVisible(migration.bankName);
            await this.toBeVisible(migration.bankIban);
            await this.toBeVisible(migration.becomeAVendor);
        }
    }

    // view geolocation filter form ([dokan-geolocation-filter-form])
    async viewGeolocationFilterForm(link: string): Promise<void> {
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        // radiusSlider is excluded — it is not asserted visible in the reference flow.
        //
        // selectCategory ('#dokan-geo-product-categories-root') is also excluded on a
        // standalone shortcode page: the category filter moved to a React
        // `TreeSelectControl` whose script (`dokan-geo-product-categories`) is enqueued
        // ONLY on shop / store-listing / product-category / product-tag contexts
        // (dokan-pro/modules/geolocation/module.php::enqueue_scripts). On a plain page
        // created from the shortcode the script + its `dokanGeoProductCategories` data are
        // never loaded (verified against the live page HTML), so the root div stays empty
        // (0px height → hidden) and never mounts. The server-rendered store-category column
        // (`.dokan-geo-store-categories`) is likewise kept `dokan-hide` by the filter JS in
        // this context. The remaining controls (form, product search, location, search
        // button) render and are asserted below.
        const { radiusSlider, selectCategory, ...filters } = shortcodesSelectors.shop.filters;
        await this.multipleElementVisible(filters);
    }

    // view advertised products ([dokan_product_advertisement])
    async viewAdvertisedProducts(link: string): Promise<void> {
        const productCard = shortcodesSelectors.shop.productCard;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        const productCount = await this.getElementCount(productCard.card);
        if (productCount) {
            await this.notToHaveCount(productCard.card, 0);
            await this.notToHaveCount(productCard.productDetailsLink, 0);
            await this.notToHaveCount(productCard.productTitle, 0);
            await this.notToHaveCount(productCard.productPrice, 0);
            await this.notToHaveCount(productCard.addToCart, 0);
        }
    }

    // view stores ([dokan-stores])
    async viewStores(link: string): Promise<void> {
        const storeList = shortcodesSelectors.storeList;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        // map elements are visible (Pro geolocation)
        if (DOKAN_PRO) {
            const { storeOnMap, ...map } = storeList.map;
            await this.multipleElementVisible(map);
        }

        // store filter elements are visible
        const { filterDetails, ...filters } = storeList.filters;
        await this.multipleElementVisible(filters);

        // open the filter panel
        await this.page.locator(storeList.filters.filterButton).click();

        // store filter detail elements are visible
        if (!DOKAN_PRO) {
            await this.toBeVisible(storeList.filters.filterDetails.searchVendor);
            await this.toBeVisible(storeList.filters.filterDetails.apply);
        } else {
            const { rating, ...proFilterDetails } = storeList.filters.filterDetails;
            await this.multipleElementVisible(proFilterDetails);
        }

        // store card elements are visible
        await this.notToHaveCount(storeList.storeCard.storeCardDiv, 0);
        // card header
        await this.notToHaveCount(storeList.storeCard.storeCardHeader, 0);
        await this.notToHaveCount(storeList.storeCard.storeBanner, 0);
        // card content
        await this.notToHaveCount(storeList.storeCard.storeCardContent, 0);
        await this.notToHaveCount(storeList.storeCard.storeData, 0);
        // card footer
        await this.notToHaveCount(storeList.storeCard.storeCardFooter, 0);
        await this.notToHaveCount(storeList.storeCard.storeAvatar, 0);
        await this.notToHaveCount(storeList.storeCard.visitStore, 0);
        if (DOKAN_PRO) {
            await this.notToHaveCount(storeList.storeCard.followUnFollowButton, 0);
        }
    }

    // view my orders ([dokan-my-orders])
    async viewMyOrders(link: string): Promise<void> {
        const myOrders = shortcodesSelectors.myOrders;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        const noOrders = await this.isVisible(myOrders.noOrdersFound);
        if (noOrders) {
            await this.toContainText(myOrders.noOrdersFound, 'No orders found!');
            console.log('No orders found on my order page');
        } else {
            await this.toBeVisible(myOrders.recentOrdersText);
            await this.multipleElementVisible(myOrders.table);
        }
    }

    // view request for quote ([dokan-request-quote])
    async viewRequestQuote(link: string): Promise<void> {
        const requestForQuote = shortcodesSelectors.requestForQuote;
        await this.page.goto(link, { waitUntil: 'domcontentloaded' });

        const noQuote = await this.isVisible(requestForQuote.noQuotesFound);
        if (noQuote) {
            await this.toContainText(requestForQuote.noQuotesFound, 'Your quote is currently empty.');
            console.log('No quotes found on request for quote page');
            await this.toBeVisible(requestForQuote.returnToShop);
        } else {
            // quote item table details are visible
            await this.multipleElementVisible(requestForQuote.quoteItemDetailsTable);
            // quote total details are visible
            await this.multipleElementVisible(requestForQuote.quoteTotals);
            // update quote is visible
            await this.toBeVisible(requestForQuote.updateQuote);
        }
    }
}
