name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
projects: ["dokan-plugin"]
assignees:
  - dokan
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Bug Description
      description: In a few sentences or paragraphs, describe the bug in detail. Include information such as what the bug does, what was expected, steps to reproduce the bug, any error messages, and the impact of the bug on the application.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Step To Reproduce
      description: List step-by-step instructions to reproduce the bug. This helps the assigned team member understand and replicate the issue.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: logs2
    attributes:
      label: Expected Behaviour
      description: Describe what you expected to happen when performing the steps listed above.
    validations:
      required: true
  - type: textarea
    id: logs3
    attributes:
      label: Actual Behaviour
      description: Describe what actually happened when performing the steps, highlighting the bug's behavior.
    validations:
      required: true
  - type: textarea
    id: logs4
    attributes:
      label: Additional Information
      description: Include any other relevant information, any images or videos, such as related issues, links to documentation, or any workarounds if they exist.
  - type: textarea
    id: logs5
    attributes:
      label: Environment (please complete the following information)
      value: |
        1. Dokan Version: [e.g. v3.1.2]
        2. Dokan Pro Version: [e.g. v3.1.2]
        3. WooCommerce Version: [e.g. v4.9.2]
        4. Browser [e.g. chrome, safari]
        5. Current Theme: [e.g. Store Front]
      render: shell
