name: Feature Request
description: File a feature request
projects: ["dokan-plugin"]
assignees:
  - dokan
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when....
    validations:
      required: true
  - type: textarea
    id: what-happened1
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: what-happened2
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: what-happened3
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  